name: Test

on: [push, pull_request]

jobs:
  test_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running tests with CPP compiler
        run: |
          cd ${{ github.workspace }}
          python3 test.py

      - name: Running tests with self-hosted compiler
        run: |
          cd ${{ github.workspace }}
          python3 test.py -s
